name: Haskell CI

on:
  push:
  pull_request:
  schedule:
    # Everyday at 4:00 AM
    - cron: "0 4 * * *"

jobs:
  build:
    name: Build executable
    defaults:
      run:
        shell: devx {0}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install GHC and Cabal
        uses: input-output-hk/actions/devx@latest
        with:
          platform: x86_64-linux
          target-platform: ""
          compiler-nix-name: ghc8107
          minimal: false
          iog: true
      - name: cabal update
        run: cabal update
      - name: cabal build dependencies
        run: cabal build all -j --enable-tests --only-dependencies
      - name: cabal build
        run: cabal build all -j --enable-tests
