name: Haskell CI

on:
  push:
  pull_request:
  schedule:
    # Everyday at 4:00 AM
    - cron: "0 4 * * *"

jobs:
  build:
    name: Build executable
    defaults:
      run:
        shell: devx {0}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler-nix-name: [ghc8107]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install GHC and Cabal
        uses: input-output-hk/actions/devx@latest
        with:
          platform: ${{ matrix.os == 'ubuntu-latest' && 'x86_64-linux' || 'x86_64-darwin' }}
          target-platform: ""
          compiler-nix-name: ${{ matrix.compiler-nix-name }}
          minimal: false
          iog: true
      - name: cabal update
        run: cabal update
      - name: cache cabal
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal-devx/packages
            ~/.cabal-devx/store
          key: ${{ runner.os }}-${{ matrix.compiler-nix-name }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.compiler-nix-name }}-
      - name: cabal build dependencies
        run: cabal build all -j --enable-tests --only-dependencies
      - name: cabal build
        run: cabal build all -j --enable-tests
